// <auto-generated>
// This file was generated from EEBus_SPINE_TS_ActuatorLevel.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ActuatorLevelFctEnumType
    {
        start,
        up,
        down,
        stop,
        percentageAbsolute,
        percentageRelative,
        absolute,
        relative
    }

    public record ActuatorLevelDataType(
        ActuatorLevelFctEnumType? Function,
        decimal? Value
    );

    public record ActuatorLevelDataElementsType(
        string? Function,
        decimal? Value
    );

    public record ActuatorLevelDescriptionDataType(
        string? Label,
        string? Description,
        string? LevelDefaultUnit
    );

    public record ActuatorLevelDescriptionDataElementsType(
        string? Label,
        string? Description,
        string? LevelDefaultUnit
    );
}
// </auto-generated>
