// <auto-generated>
// This file was generated from EEBus_SPINE_TS_ActuatorSwitch.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ActuatorSwitchFctEnumType
    {
        on,
        off,
        toggle
    }

    public record ActuatorSwitchDataType(
        ActuatorSwitchFctEnumType? Function
    );

    public record ActuatorSwitchDataElementsType(
        string? Function
    );

    public record ActuatorSwitchDescriptionDataType(
        string? Label,
        string? Description
    );

    public record ActuatorSwitchDescriptionDataElementsType(
        string? Label,
        string? Description
    );
}
// </auto-generated>
