// <auto-generated>
// This file was generated from EEBus_SPINE_TS_Alarm.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum AlarmTypeEnumType
    {
        alarmCancelled,
        underThreshold,
        overThreshold
    }

    public record AlarmDataType(
        uint? AlarmId,
        uint? ThresholdId,
        string? Timestamp,
        AlarmTypeEnumType? AlarmType,
        decimal? MeasuredValue,
        string? EvaluationPeriod,
        string? ScopeType,
        string? Label,
        string? Description
    );

    public record AlarmDataElementsType(
        string? AlarmId,
        string? ThresholdId,
        string? Timestamp,
        string? AlarmType,
        decimal? MeasuredValue,
        string? EvaluationPeriod,
        string? ScopeType,
        string? Label,
        string? Description
    );

    public record AlarmListDataType(
        AlarmDataType[]? AlarmData
    );

    public record AlarmListDataSelectorsType(
        uint? AlarmId,
        string? ScopeType
    );
}
// </auto-generated>
