// <auto-generated>
// This file was generated from EEBus_SPINE_TS_Bill.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum BillTypeEnumType
    {
        chargingSummary
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum BillPositionTypeEnumType
    {
        gridElectricEnergy,
        selfProducedElectricEnergy
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum BillCostTypeEnumType
    {
        absolutePrice,
        relativePrice,
        co2Emission,
        renewableEnergy,
        radioactiveWaste
    }

    public record BillValueType(
        uint? ValueId,
        string? Unit,
        decimal? Value,
        decimal? ValuePercentage
    );

    public record BillValueElementsType(
        string? ValueId,
        string? Unit,
        decimal? Value,
        decimal? ValuePercentage
    );

    public record BillCostType(
        uint? CostId,
        BillCostTypeEnumType? CostType,
        uint? ValueId,
        string? Unit,
        string? Currency,
        decimal? Cost,
        decimal? CostPercentage
    );

    public record BillCostElementsType(
        string? CostId,
        string? CostType,
        string? ValueId,
        string? Unit,
        string? Currency,
        decimal? Cost,
        decimal? CostPercentage
    );

    public record BillPositionType(
        uint? PositionId,
        BillPositionTypeEnumType? PositionType,
        string? TimePeriod,
        BillValueType[]? Value,
        BillCostType[]? Cost,
        string? Label,
        string? Description
    );

    public record BillPositionElementsType(
        string? PositionId,
        string? PositionType,
        string? TimePeriod,
        BillValueElementsType? Value,
        BillCostElementsType? Cost,
        string? Label,
        string? Description
    );

    public record BillDataType(
        uint? BillId,
        BillTypeEnumType? BillType,
        string? ScopeType,
        BillPositionType? Total,
        BillPositionType[]? Position
    );

    public record BillDataElementsType(
        string? BillId,
        string? BillType,
        string? ScopeType,
        BillPositionElementsType? Total,
        BillPositionElementsType? Position
    );

    public record BillListDataType(
        BillDataType[]? BillData
    );

    public record BillListDataSelectorsType(
        uint? BillId,
        string? ScopeType
    );

    public record BillConstraintsDataType(
        uint? BillId,
        uint? PositionCountMin,
        uint? PositionCountMax
    );

    public record BillConstraintsDataElementsType(
        string? BillId,
        string? PositionCountMin,
        string? PositionCountMax
    );

    public record BillConstraintsListDataType(
        BillConstraintsDataType[]? BillConstraintsData
    );

    public record BillConstraintsListDataSelectorsType(
        uint? BillId
    );

    public record BillDescriptionDataType(
        uint? BillId,
        bool? BillWriteable,
        bool? UpdateRequired,
        BillTypeEnumType[]? SupportedBillType,
        string? SessionId
    );

    public record BillDescriptionDataElementsType(
        string? BillId,
        string? BillWriteable,
        string? UpdateRequired,
        string? SupportedBillType,
        string? SessionId
    );

    public record BillDescriptionListDataType(
        BillDescriptionDataType[]? BillDescriptionData
    );

    public record BillDescriptionListDataSelectorsType(
        uint? BillId
    );
}
// </auto-generated>
