// <auto-generated>
// This file was generated from EEBus_SPINE_TS_BindingManagement.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record BindingManagementEntryDataType(
        uint? BindingId,
        string? ClientAddress,
        string? ServerAddress,
        string? Label,
        string? Description
    );

    public record BindingManagementEntryDataElementsType(
        string? BindingId,
        string? ClientAddress,
        string? ServerAddress,
        string? Label,
        string? Description
    );

    public record BindingManagementEntryListDataType(
        BindingManagementEntryDataType[]? BindingManagementEntryData
    );

    public record BindingManagementEntryListDataSelectorsType(
        uint? BindingId,
        string? ClientAddress,
        string? ServerAddress
    );

    public record BindingManagementRequestCallType(
        string? ClientAddress,
        string? ServerAddress,
        string? ServerFeatureType
    );

    public record BindingManagementRequestCallElementsType(
        string? ClientAddress,
        string? ServerAddress,
        string? ServerFeatureType
    );

    public record BindingManagementDeleteCallType(
        uint? BindingId,
        string? ClientAddress,
        string? ServerAddress
    );

    public record BindingManagementDeleteCallElementsType(
        string? BindingId,
        string? ClientAddress,
        string? ServerAddress
    );
}
// </auto-generated>
