// <auto-generated>
// This file was generated from EEBus_SPINE_TS_CommandCommonDefinitions.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    // This file contains only groupings and includes, not concrete types.
    // All referenced types are defined in their respective files.
}
// </auto-generated>
