// <auto-generated>
// This file was generated from EEBus_SPINE_TS_CommonDataTypes.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum RecurringIntervalEnumType
    {
        yearly,
        monthly,
        weekly,
        daily,
        hourly,
        everyMinute,
        everySecond
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum MonthType
    {
        january,
        february,
        march,
        april,
        may,
        june,
        july,
        august,
        september,
        october,
        november,
        december
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum DayOfWeekType
    {
        monday,
        tuesday,
        wednesday,
        thursday,
        friday,
        saturday,
        sunday
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum OccurrenceEnumType
    {
        first,
        second,
        third,
        fourth,
        last
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum CommodityTypeEnumType
    {
        electricity,
        gas,
        oil,
        water,
        wasteWater,
        domesticHotWater,
        heatingWater,
        steam,
        heat,
        coolingLoad,
        air
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum EnergyDirectionEnumType
    {
        consume,
        produce
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum EnergyModeEnumType
    {
        consume,
        produce,
        idle,
        auto
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum UnitOfMeasurementEnumType
    {
        unknown,
        _1,
        m,
        kg,
        s,
        A,
        K,
        mol,
        cd,
        V,
        W,
        Wh,
        VA,
        VAh,
        var,
        varh,
        degC,
        degF,
        Lm,
        lx,
        Ohm,
        Hz,
        dB,
        dBm,
        pct,
        ppm,
        l,
        l_s,
        l_h,
        deg,
        rad,
        rad_s,
        sr,
        Gy,
        Bq,
        Bq_m3,
        Sv,
        Rd,
        C,
        F,
        H,
        J,
        N,
        N_m,
        N_s,
        Wb,
        T,
        Pa,
        bar,
        atm,
        psi,
        mmHg,
        m2,
        m3,
        m3_h,
        m_s,
        m_s2,
        m3_s,
        m_m3,
        kg_m3,
        kg_m,
        m2_s,
        W_m_K,
        J_K,
        _1_s,
        W_m2,
        J_m2,
        S,
        S_m,
        K_s,
        Pa_s,
        J_kg_K,
        Vs,
        V_m,
        V_Hz,
        As,
        A_m,
        Hz_s,
        kg_s,
        kg_m2,
        J_Wh,
        W_s,
        ft3,
        ft3_h,
        ccf,
        ccf_h,
        US_liq_gal,
        US_liq_gal_h,
        Imp_gal,
        Imp_gal_h,
        Btu,
        Btu_h,
        Ah,
        kg_Wh
    }

    // ...additional types omitted for brevity...
}
// </auto-generated>
