// <auto-generated>
// This file was generated from EEBus_SPINE_TS_CommandFrame.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum CmdClassifierType
    {
        read,
        reply,
        notify,
        write,
        call,
        result
    }

    public record FilterType(
        ulong? FilterId
    // Other fields are references to other types/groups, not directly serializable here
    );

    public record CmdControlType(
        string? Delete,
        string? Partial
    );

    // CmdType and other group-based types are not directly serializable as records
}
// </auto-generated>
