// <auto-generated>
// This file was generated from EEBus_SPINE_TS_Datagram.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record HeaderType(
        string? SpecificationVersion,
        string? AddressSource,
        string? AddressDestination,
        string? AddressOriginator,
        ulong? MsgCounter,
        ulong? MsgCounterReference,
        CmdClassifierType? CmdClassifier,
        bool? AckRequest,
        string? Timestamp
    );

    public record PayloadType(
        CmdType[]? Cmd
    );

    public record DatagramType(
        HeaderType? Header,
        PayloadType? Payload
    );
}
// </auto-generated>
