// <auto-generated>
// This file was generated from EEBus_SPINE_TS_DataTunneling.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record DataTunnelingHeaderType(
        string? PurposeId,
        uint? ChannelId,
        uint? SequenceId
    );

    public record DataTunnelingHeaderElementsType(
        string? PurposeId,
        string? ChannelId,
        string? SequenceId
    );

    public record DataTunnelingCallType(
        DataTunnelingHeaderType? Header,
        byte[]? Payload
    );

    public record DataTunnelingCallElementsType(
        DataTunnelingHeaderElementsType? Header,
        string? Payload
    );
}
// </auto-generated>
