// <auto-generated>
// This file was generated from EEBus_SPINE_TS_DeviceClassification.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum PowerSourceEnumType
    {
        unknown,
        mainsSinglePhase,
        mains3Phase,
        battery,
        dc
    }

    public record DeviceClassificationManufacturerDataType(
        string? DeviceName,
        string? DeviceCode,
        string? SerialNumber,
        string? SoftwareRevision,
        string? HardwareRevision,
        string? VendorName,
        string? VendorCode,
        string? BrandName,
        PowerSourceEnumType? PowerSource,
        string? ManufacturerNodeIdentification,
        string? ManufacturerLabel,
        string? ManufacturerDescription
    );

    public record DeviceClassificationManufacturerDataElementsType(
        string? DeviceName,
        string? DeviceCode,
        string? SerialNumber,
        string? SoftwareRevision,
        string? HardwareRevision,
        string? VendorName,
        string? VendorCode,
        string? BrandName,
        string? PowerSource,
        string? ManufacturerNodeIdentification,
        string? ManufacturerLabel,
        string? ManufacturerDescription
    );

    public record DeviceClassificationUserDataType(
        string? UserNodeIdentification,
        string? UserLabel,
        string? UserDescription
    );

    public record DeviceClassificationUserDataElementsType(
        string? UserNodeIdentification,
        string? UserLabel,
        string? UserDescription
    );
}
// </auto-generated>
