// <auto-generated>
// This file was generated from EEBus_SPINE_TS_DeviceConfiguration.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum DeviceConfigurationKeyNameEnumType
    {
        peakPowerOfPvSystem,
        pvCurtailmentLimitFactor,
        asymmetricChargingSupported,
        communicationsStandard,
        inverterGridCode,
        pvStringAvailabilityStatus,
        batteryAvailabilityStatus,
        gridConnectionStatus,
        timeToAcChargePowerMax,
        timeToAcDischargePowerMax,
        tilt,
        azimuth,
        batteryType,
        maxCycleCountPerDay,
        failsafeConsumptionActivePowerLimit,
        failsafeProductionActivePowerLimit,
        failsafePositiveReactivePowerLimit,
        failsafeNegativeReactivePowerLimit,
        failsafePositiveCosPhiLimit,
        failsafeNegativeCosPhiLimit,
        maxAcChargePower,
        maxAcDischargePower,
        maxDcChargePower,
        maxDcDischargePower,
        batteryActiveControlMode,
        defaultAcPower,
        defaultDcPower,
        defaultPccPower,
        failsafeAcPowerSetpoint,
        failsafeDcPowerSetpoint,
        failsafePccPowerSetpoint,
        failsafeDurationMinimum,
        dischargingBelowTargetEnergyRequestPermitted,
        incentivesSimulationCyclesMax,
        incentivesSimulationConcurrent,
        incentivesTimeoutIncentiveRequest,
        incentivesWaitIncentiveWriteable
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum DeviceConfigurationKeyValueTypeType
    {
        boolean,
        date,
        dateTime,
        duration,
        @string,
        time,
        scaledNumber,
        integer
    }

    public record DeviceConfigurationKeyValueValueType(
        bool? Boolean,
        string? Date,
        string? DateTime,
        string? Duration,
        string? String,
        string? Time,
        decimal? ScaledNumber,
        long? Integer
    );

    public record DeviceConfigurationKeyValueValueElementsType(
        string? Boolean,
        string? Date,
        string? DateTime,
        string? Duration,
        string? String,
        string? Time,
        decimal? ScaledNumber
    );

    public record DeviceConfigurationKeyValueDataType(
        uint? KeyId,
        DeviceConfigurationKeyValueValueType? Value,
        bool? IsValueChangeable
    );

    public record DeviceConfigurationKeyValueDataElementsType(
        string? KeyId,
        DeviceConfigurationKeyValueValueElementsType? Value,
        string? IsValueChangeable
    );

    public record DeviceConfigurationKeyValueListDataType(
        DeviceConfigurationKeyValueDataType[]? DeviceConfigurationKeyValueData
    );

    public record DeviceConfigurationKeyValueListDataSelectorsType(
        uint? KeyId
    );

    public record DeviceConfigurationKeyValueDescriptionDataType(
        uint? KeyId,
        DeviceConfigurationKeyNameEnumType? KeyName,
        DeviceConfigurationKeyValueTypeType? ValueType,
        string? Unit,
        string? Label,
        string? Description
    );

    public record DeviceConfigurationKeyValueDescriptionDataElementsType(
        string? KeyId,
        string? KeyName,
        string? ValueType,
        string? Unit,
        string? Label,
        string? Description
    );

    public record DeviceConfigurationKeyValueDescriptionListDataType(
        DeviceConfigurationKeyValueDescriptionDataType[]? DeviceConfigurationKeyValueDescriptionData
    );

    public record DeviceConfigurationKeyValueDescriptionListDataSelectorsType(
        uint? KeyId,
        DeviceConfigurationKeyNameEnumType? KeyName
    );

    public record DeviceConfigurationKeyValueConstraintsDataType(
        uint? KeyId,
        DeviceConfigurationKeyValueValueType? ValueRangeMin,
        DeviceConfigurationKeyValueValueType? ValueRangeMax,
        DeviceConfigurationKeyValueValueType? ValueStepSize
    );

    public record DeviceConfigurationKeyValueConstraintsDataElementsType(
        string? KeyId,
        DeviceConfigurationKeyValueValueElementsType? ValueRangeMin,
        DeviceConfigurationKeyValueValueElementsType? ValueRangeMax,
        DeviceConfigurationKeyValueValueElementsType? ValueStepSize
    );

    public record DeviceConfigurationKeyValueConstraintsListDataType(
        DeviceConfigurationKeyValueConstraintsDataType[]? DeviceConfigurationKeyValueConstraintsData
    );

    public record DeviceConfigurationKeyValueConstraintsListDataSelectorsType(
        uint? KeyId
    );
}
// </auto-generated>
