// <auto-generated>
// This file was generated from EEBus_SPINE_TS_DeviceDiagnosis.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum DeviceDiagnosisOperatingStateEnumType
    {
        normalOperation,
        standby,
        failure,
        serviceNeeded,
        overrideDetected,
        inAlarm,
        notReachable,
        finished,
        temporarilyNotReady,
        off
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum PowerSupplyConditionEnumType
    {
        good,
        low,
        critical,
        unknown,
        error
    }

    public record DeviceDiagnosisStateDataType(
        string? Timestamp,
        DeviceDiagnosisOperatingStateEnumType? OperatingState,
        string? VendorStateCode,
        string? LastErrorCode,
        string? UpTime,
        string? TotalUpTime,
        PowerSupplyConditionEnumType? PowerSupplyCondition
    );

    public record DeviceDiagnosisStateDataElementsType(
        string? Timestamp,
        string? OperatingState,
        string? VendorStateCode,
        string? LastErrorCode,
        string? UpTime,
        string? TotalUpTime,
        string? PowerSupplyCondition
    );

    public record DeviceDiagnosisHeartbeatDataType(
        string? Timestamp,
        ulong? HeartbeatCounter,
        string? HeartbeatTimeout
    );

    public record DeviceDiagnosisHeartbeatDataElementsType(
        string? Timestamp,
        string? HeartbeatCounter,
        string? HeartbeatTimeout
    );

    public record DeviceDiagnosisServiceDataType(
        string? Timestamp,
        string? InstallationTime,
        ulong? BootCounter,
        string? NextService
    );

    public record DeviceDiagnosisServiceDataElementsType(
        string? Timestamp,
        string? InstallationTime,
        string? BootCounter,
        string? NextService
    );
}
// </auto-generated>
