// <auto-generated>
// This file was generated from EEBus_SPINE_TS_DirectControl.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum DirectControlActivityStateEnumType
    {
        running,
        paused,
        inactive
    }

    public record DirectControlActivityDataType(
        string? Timestamp,
        DirectControlActivityStateEnumType? ActivityState,
        bool? IsActivityStateChangeable,
        string? EnergyMode,
        bool? IsEnergyModeChangeable,
        decimal? Power,
        bool? IsPowerChangeable,
        decimal? Energy,
        bool? IsEnergyChangeable,
        string? SequenceId
    );

    public record DirectControlActivityDataElementsType(
        string? Timestamp,
        string? ActivityState,
        string? IsActivityStateChangeable,
        string? EnergyMode,
        string? IsEnergyModeChangeable,
        decimal? Power,
        string? IsPowerChangeable,
        decimal? Energy,
        string? IsEnergyChangeable,
        string? SequenceId
    );

    public record DirectControlActivityListDataType(
        DirectControlActivityDataType[]? DirectControlActivityData
    );

    public record DirectControlActivityListDataSelectorsType(
        string? TimestampInterval
    );

    public record DirectControlDescriptionDataType(
        string? PositiveEnergyDirection,
        string? PowerUnit,
        string? EnergyUnit
    );

    public record DirectControlDescriptionDataElementsType(
        string? PositiveEnergyDirection,
        string? PowerUnit,
        string? EnergyUnit
    );
}
// </auto-generated>
