// <auto-generated>
// This file was generated from EEBus_SPINE_TS_ElectricalConnection.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ElectricalConnectionMeasurandVariantEnumType
    {
        amplitude,
        rms,
        instantaneous,
        angle,
        cosPhi
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ElectricalConnectionVoltageTypeEnumType
    {
        ac,
        dc
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ElectricalConnectionAcMeasurementTypeEnumType
    {
        real,
        reactive,
        apparent,
        phase
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ElectricalConnectionPhaseNameEnumType
    {
        a,
        b,
        c,
        ab,
        bc,
        ac,
        abc,
        neutral,
        ground,
        none
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ElectricalConnectionConnectionPointType
    {
        grid,
        home,
        pv,
        sd,
        other
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ElectricalConnectionCharacteristicContextEnumType
    {
        device,
        entity,
        inverter,
        pvString,
        battery
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ElectricalConnectionCharacteristicTypeEnumType
    {
        powerConsumptionMin,
        powerConsumptionMax,
        powerConsumptionNominalMin,
        powerConsumptionNominalMax,
        powerProductionMin,
        powerProductionMax,
        powerProductionNominalMin,
        powerProductionNominalMax,
        energyCapacityNominalMax,
        contractualConsumptionNominalMax,
        contractualProductionNominalMax,
        apparentPowerProductionNominalMax,
        apparentPowerConsumptionNominalMax
    }

    public record ElectricalConnectionParameterDescriptionDataType(
        uint? ElectricalConnectionId,
        uint? ParameterId,
        uint? MeasurementId,
        ElectricalConnectionVoltageTypeEnumType? VoltageType,
        ElectricalConnectionPhaseNameEnumType? AcMeasuredPhases,
        ElectricalConnectionPhaseNameEnumType? AcMeasuredInReferenceTo,
        ElectricalConnectionAcMeasurementTypeEnumType? AcMeasurementType,
        ElectricalConnectionMeasurandVariantEnumType? AcMeasurementVariant,
        byte? AcMeasuredHarmonic,
        string? ScopeType,
        string? Label,
        string? Description
    );

    public record ElectricalConnectionParameterDescriptionDataElementsType(
        string? ElectricalConnectionId,
        string? ParameterId,
        string? MeasurementId,
        string? VoltageType,
        string? AcMeasuredPhases,
        string? AcMeasuredInReferenceTo,
        string? AcMeasurementType,
        string? AcMeasurementVariant,
        string? AcMeasuredHarmonic,
        string? ScopeType,
        string? Label,
        string? Description
    );

    public record ElectricalConnectionParameterDescriptionListDataType(
        ElectricalConnectionParameterDescriptionDataType[]? ElectricalConnectionParameterDescriptionData
    );

    public record ElectricalConnectionParameterDescriptionListDataSelectorsType(
        uint? ElectricalConnectionId,
        uint? ParameterId,
        uint? MeasurementId,
        string? ScopeType
    );

    public record ElectricalConnectionPermittedValueSetDataType(
        uint? ElectricalConnectionId,
        uint? ParameterId,
        decimal[]? PermittedValueSet
    );

    public record ElectricalConnectionPermittedValueSetDataElementsType(
        string? ElectricalConnectionId,
        string? ParameterId,
        string? PermittedValueSet
    );

    public record ElectricalConnectionPermittedValueSetListDataType(
        ElectricalConnectionPermittedValueSetDataType[]? ElectricalConnectionPermittedValueSetData
    );

    public record ElectricalConnectionPermittedValueSetListDataSelectorsType(
        uint? ElectricalConnectionId,
        uint? ParameterId
    );

    public record ElectricalConnectionCharacteristicDataType(
        uint? ElectricalConnectionId,
        uint? ParameterId,
        uint? CharacteristicId,
        ElectricalConnectionCharacteristicContextEnumType? CharacteristicContext,
        ElectricalConnectionCharacteristicTypeEnumType? CharacteristicType,
        decimal? Value,
        string? Unit
    );

    public record ElectricalConnectionCharacteristicDataElementsType(
        string? ElectricalConnectionId,
        string? ParameterId,
        string? CharacteristicId,
        string? CharacteristicContext,
        string? CharacteristicType,
        string? Value,
        string? Unit
    );

    public record ElectricalConnectionCharacteristicListDataType(
        ElectricalConnectionCharacteristicDataType[]? ElectricalConnectionCharacteristicData
    );

    public record ElectricalConnectionCharacteristicListDataSelectorsType(
        uint? ElectricalConnectionId,
        uint? ParameterId,
        uint? CharacteristicId,
        ElectricalConnectionCharacteristicContextEnumType? CharacteristicContext,
        ElectricalConnectionCharacteristicTypeEnumType? CharacteristicType
    );

    public record ElectricalConnectionStateDataType(
        uint? ElectricalConnectionId,
        string? Timestamp,
        string? CurrentEnergyMode,
        string? ConsumptionTime,
        string? ProductionTime,
        string? TotalConsumptionTime,
        string? TotalProductionTime
    );

    public record ElectricalConnectionStateDataElementsType(
        string? ElectricalConnectionId,
        string? Timestamp,
        string? CurrentEnergyMode,
        string? ConsumptionTime,
        string? ProductionTime,
        string? TotalConsumptionTime,
        string? TotalProductionTime
    );

    public record ElectricalConnectionStateListDataType(
        ElectricalConnectionStateDataType[]? ElectricalConnectionStateData
    );

    public record ElectricalConnectionStateListDataSelectorsType(
        uint? ElectricalConnectionId
    );

    public record ElectricalConnectionDescriptionDataType(
        uint? ElectricalConnectionId,
        ElectricalConnectionVoltageTypeEnumType? PowerSupplyType,
        uint? AcConnectedPhases,
        string? AcRmsPeriodDuration,
        string? PositiveEnergyDirection,
        string? ScopeType,
        string? Label,
        string? Description
    );

    public record ElectricalConnectionDescriptionDataElementsType(
        string? ElectricalConnectionId,
        string? PowerSupplyType,
        string? AcConnectedPhases,
        string? AcRmsPeriodDuration,
        string? PositiveEnergyDirection,
        string? ScopeType,
        string? Label,
        string? Description
    );

    public record ElectricalConnectionDescriptionListDataType(
        ElectricalConnectionDescriptionDataType[]? ElectricalConnectionDescriptionData
    );

    public record ElectricalConnectionDescriptionListDataSelectorsType(
        uint? ElectricalConnectionId,
        string? ScopeType
    );
}
