// <auto-generated>
// This file was generated from EEBus_SPINE_TS_HVAC.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum HvacSystemFunctionTypeEnumType
    {
        heating,
        cooling,
        ventilation,
        dhw
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum HvacOperationModeTypeEnumType
    {
        auto,
        on,
        off,
        eco
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum HvacOverrunTypeEnumType
    {
        oneTimeDhw,
        party,
        sgReadyCondition1,
        sgReadyCondition3,
        sgReadyCondition4,
        oneDayAway,
        oneDayAtHome,
        oneTimeVentilation,
        hvacSystemOff,
        valveKick
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum HvacOverrunStatusEnumType
    {
        active,
        running,
        finished,
        inactive
    }

    public record HvacSystemFunctionDataType(
        uint? SystemFunctionId,
        uint? CurrentOperationModeId,
        bool? IsOperationModeIdChangeable,
        uint? CurrentSetpointId,
        bool? IsSetpointIdChangeable,
        bool? IsOverrunActive
    );

    public record HvacSystemFunctionDataElementsType(
        string? SystemFunctionId,
        string? CurrentOperationModeId,
        string? IsOperationModeIdChangeable,
        string? CurrentSetpointId,
        string? IsSetpointIdChangeable,
        string? IsOverrunActive
    );

    public record HvacSystemFunctionListDataType(
        HvacSystemFunctionDataType[]? HvacSystemFunctionData
    );

    public record HvacSystemFunctionListDataSelectorsType(
        uint? SystemFunctionId
    );

    public record HvacSystemFunctionOperationModeRelationDataType(
        uint? SystemFunctionId,
        uint[]? OperationModeId
    );

    public record HvacSystemFunctionOperationModeRelationDataElementsType(
        string? SystemFunctionId,
        string? OperationModeId
    );

    public record HvacSystemFunctionOperationModeRelationListDataType(
        HvacSystemFunctionOperationModeRelationDataType[]? HvacSystemFunctionOperationModeRelationData
    );

    public record HvacSystemFunctionOperationModeRelationListDataSelectorsType(
        uint? SystemFunctionId
    );

    public record HvacSystemFunctionSetpointRelationDataType(
        uint? SystemFunctionId,
        uint? OperationModeId,
        uint[]? SetpointId
    );

    public record HvacSystemFunctionSetpointRelationDataElementsType(
        string? SystemFunctionId,
        string? OperationModeId,
        string? SetpointId
    );

    public record HvacSystemFunctionSetpointRelationListDataType(
        HvacSystemFunctionSetpointRelationDataType[]? HvacSystemFunctionSetpointRelationData
    );

    public record HvacSystemFunctionSetpointRelationListDataSelectorsType(
        uint? SystemFunctionId,
        uint? OperationModeId
    );

    public record HvacSystemFunctionPowerSequenceRelationDataType(
        uint? SystemFunctionId,
        uint[]? SequenceId
    );

    public record HvacSystemFunctionPowerSequenceRelationDataElementsType(
        string? SystemFunctionId,
        string? SequenceId
    );

    public record HvacSystemFunctionPowerSequenceRelationListDataType(
        HvacSystemFunctionPowerSequenceRelationDataType[]? HvacSystemFunctionPowerSequenceRelationData
    );

    public record HvacSystemFunctionPowerSequenceRelationListDataSelectorsType(
        uint? SystemFunctionId
    );

    public record HvacSystemFunctionDescriptionDataType(
        uint? SystemFunctionId,
        HvacSystemFunctionTypeEnumType? SystemFunctionType,
        string? Label,
        string? Description
    );

    public record HvacSystemFunctionDescriptionDataElementsType(
        string? SystemFunctionId,
        string? SystemFunctionType,
        string? Label,
        string? Description
    );

    public record HvacSystemFunctionDescriptionListDataType(
        HvacSystemFunctionDescriptionDataType[]? HvacSystemFunctionDescriptionData
    );

    public record HvacSystemFunctionDescriptionListDataSelectorsType(
        uint? SystemFunctionId
    );

    public record HvacOperationModeDescriptionDataType(
        uint? OperationModeId,
        HvacOperationModeTypeEnumType? OperationModeType,
        string? Label,
        string? Description
    );

    public record HvacOperationModeDescriptionDataElementsType(
        string? OperationModeId,
        string? OperationModeType,
        string? Label,
        string? Description
    );

    public record HvacOperationModeDescriptionListDataType(
        HvacOperationModeDescriptionDataType[]? HvacOperationModeDescriptionData
    );

    public record HvacOperationModeDescriptionListDataSelectorsType(
        uint? OperationModeId
    );

    public record HvacOverrunDataType(
        uint? OverrunId,
        HvacOverrunStatusEnumType? OverrunStatus,
        uint? TimeTableId,
        bool? IsOverrunStatusChangeable
    );

    public record HvacOverrunDataElementsType(
        string? OverrunId,
        string? OverrunStatus,
        string? TimeTableId,
        string? IsOverrunStatusChangeable
    );

    public record HvacOverrunListDataType(
        HvacOverrunDataType[]? HvacOverrunData
    );

    public record HvacOverrunListDataSelectorsType(
        uint? OverrunId
    );

    public record HvacOverrunDescriptionDataType(
        uint? OverrunId,
        HvacOverrunTypeEnumType? OverrunType,
        uint[]? AffectedSystemFunctionId,
        string? Label,
        string? Description
    );

    public record HvacOverrunDescriptionDataElementsType(
        string? OverrunId,
        string? OverrunType,
        string? AffectedSystemFunctionId,
        string? Label,
        string? Description
    );

    public record HvacOverrunDescriptionListDataType(
        HvacOverrunDescriptionDataType[]? HvacOverrunDescriptionData
    );

    public record HvacOverrunDescriptionListDataSelectorsType(
        uint? OverrunId
    );
}
