// <auto-generated>
// This file was generated from EEBus_SPINE_TS_HVAC_overview.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    // This file defines only groupings and includes, no new types.
    // All types are defined in HVAC.g.cs
}
// </auto-generated>
