// <auto-generated>
// This file was generated from EEBus_SPINE_TS_Identification.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum IdentificationTypeEnumType
    {
        eui48,
        eui64,
        userRfidTag
    }

    public record IdentificationDataType(
        uint? IdentificationId,
        IdentificationTypeEnumType? IdentificationType,
        string? IdentificationValue,
        bool? Authorized
    );

    public record IdentificationDataElementsType(
        string? IdentificationId,
        string? IdentificationType,
        string? IdentificationValue,
        string? Authorized
    );

    public record IdentificationListDataType(
        IdentificationDataType[]? IdentificationData
    );

    public record IdentificationListDataSelectorsType(
        uint? IdentificationId,
        IdentificationTypeEnumType? IdentificationType
    );

    public record SessionIdentificationDataType(
        uint? SessionId,
        uint? IdentificationId,
        bool? IsLatestSession,
        string? TimePeriod
    );

    public record SessionIdentificationDataElementsType(
        string? SessionId,
        string? IdentificationId,
        string? IsLatestSession,
        string? TimePeriod
    );

    public record SessionIdentificationListDataType(
        SessionIdentificationDataType[]? SessionIdentificationData
    );

    public record SessionIdentificationListDataSelectorsType(
        uint? SessionId,
        uint? IdentificationId,
        bool? IsLatestSession,
        string? TimePeriod
    );

    public record SessionMeasurementRelationDataType(
        uint? SessionId,
        uint[]? MeasurementId
    );

    public record SessionMeasurementRelationDataElementsType(
        string? SessionId,
        string? MeasurementId
    );

    public record SessionMeasurementRelationListDataType(
        SessionMeasurementRelationDataType[]? SessionMeasurementRelationData
    );

    public record SessionMeasurementRelationListDataSelectorsType(
        uint? SessionId,
        uint? MeasurementId
    );
}
