// <auto-generated>
// This file was generated from EEBus_SPINE_TS_IncentiveTable.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    // Note: Many types referenced here (TariffDataType, ScaledNumberType, etc.) are defined in other generated files.

    public record IncentiveTableType(
        TariffDataType? Tariff,
        IncentiveTableIncentiveSlotType[]? IncentiveSlot,
        IncentiveTableTierType[]? Tier
    );

    public record IncentiveTableIncentiveSlotType(
        TimeTableDataType? TimeInterval,
        IncentiveTableTierType[]? Tier
    );

    public record IncentiveTableTierType(
        TierDataType? Tier,
        TierBoundaryDataType[]? Boundary,
        IncentiveDataType[]? Incentive
    );

    public record IncentiveTableDataType(
        IncentiveTableType[]? IncentiveTable
    );

    public record IncentiveTableElementsType(
        TariffDataElementsType? Tariff,
        IncentiveTableIncentiveSlotElementsType? IncentiveSlot
    );

    public record IncentiveTableIncentiveSlotElementsType(
        TimeTableDataElementsType? TimeInterval,
        IncentiveTableTierElementsType? Tier
    );

    public record IncentiveTableTierElementsType(
        TierDataElementsType? Tier,
        TierBoundaryDataElementsType? Boundary,
        IncentiveDataElementsType? Incentive
    );

    public record IncentiveTableDataElementsType(
        IncentiveTableElementsType? IncentiveTable
    );

    public record IncentiveTableDataSelectorsType(
        TariffListDataSelectorsType? Tariff
    );

    public record IncentiveTableDescriptionType(
        TariffDescriptionDataType? TariffDescription,
        IncentiveTableDescriptionTierType[]? Tier
    );

    public record IncentiveTableDescriptionTierType(
        TierDescriptionDataType? TierDescription,
        TierBoundaryDescriptionDataType[]? BoundaryDescription,
        IncentiveDescriptionDataType[]? IncentiveDescription
    );

    // ...additional types for constraints, selectors, etc. would follow the same pattern
}
