// <auto-generated>
// This file was generated from EEBus_SPINE_TS_LoadControl.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum LoadControlEventActionEnumType
    {
        pause,
        resume,
        reduce,
        increase,
        emergency,
        normal
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum LoadControlEventStateEnumType
    {
        eventAccepted,
        eventStarted,
        eventStopped,
        eventRejected,
        eventCancelled,
        eventError
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum LoadControlLimitTypeEnumType
    {
        minValueLimit,
        maxValueLimit,
        signDependentAbsValueLimit
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum LoadControlCategoryEnumType
    {
        obligation,
        recommendation,
        optimization
    }

    public record LoadControlNodeDataType(
        bool? IsNodeRemoteControllable
    );

    public record LoadControlNodeDataElementsType(
        string? IsNodeRemoteControllable
    );

    public record LoadControlEventDataType(
        string? Timestamp,
        uint? EventId,
        LoadControlEventActionEnumType? EventActionConsume,
        LoadControlEventActionEnumType? EventActionProduce,
        string? TimePeriod
    );

    public record LoadControlEventDataElementsType(
        string? Timestamp,
        string? EventId,
        string? EventActionConsume,
        string? EventActionProduce,
        string? TimePeriod
    );

    public record LoadControlEventListDataType(
        LoadControlEventDataType[]? LoadControlEventData
    );

    public record LoadControlEventListDataSelectorsType(
        string? TimestampInterval,
        uint? EventId
    );

    public record LoadControlStateDataType(
        string? Timestamp,
        uint? EventId,
        LoadControlEventStateEnumType? EventStateConsume,
        LoadControlEventActionEnumType? AppliedEventActionConsume,
        LoadControlEventStateEnumType? EventStateProduce,
        LoadControlEventActionEnumType? AppliedEventActionProduce
    );

    public record LoadControlStateDataElementsType(
        string? Timestamp,
        string? EventId,
        string? EventStateConsume,
        string? AppliedEventActionConsume,
        string? EventStateProduce,
        string? AppliedEventActionProduce
    );

    public record LoadControlStateListDataType(
        LoadControlStateDataType[]? LoadControlStateData
    );

    public record LoadControlStateListDataSelectorsType(
        string? TimestampInterval,
        uint? EventId
    );

    public record LoadControlLimitDataType(
        uint? LimitId,
        bool? IsLimitChangeable,
        bool? IsLimitActive,
        string? TimePeriod,
        decimal? Value
    );

    public record LoadControlLimitDataElementsType(
        string? LimitId,
        string? IsLimitChangeable,
        string? IsLimitActive,
        string? TimePeriod,
        string? Value
    );

    public record LoadControlLimitListDataType(
        LoadControlLimitDataType[]? LoadControlLimitData
    );

    public record LoadControlLimitListDataSelectorsType(
        uint? LimitId
    );

    public record LoadControlLimitConstraintsDataType(
        uint? LimitId,
        decimal? ValueRangeMin,
        decimal? ValueRangeMax,
        decimal? ValueStepSize
    );

    public record LoadControlLimitConstraintsDataElementsType(
        string? LimitId,
        string? ValueRangeMin,
        string? ValueRangeMax,
        string? ValueStepSize
    );

    public record LoadControlLimitConstraintsListDataType(
        LoadControlLimitConstraintsDataType[]? LoadControlLimitConstraintsData
    );

    public record LoadControlLimitConstraintsListDataSelectorsType(
        uint? LimitId
    );

    public record LoadControlLimitDescriptionDataType(
        uint? LimitId,
        LoadControlLimitTypeEnumType? LimitType,
        LoadControlCategoryEnumType? LimitCategory,
        string? LimitDirection,
        uint? MeasurementId,
        string? Unit,
        string? ScopeType,
        string? Label,
        string? Description
    );

    public record LoadControlLimitDescriptionDataElementsType(
        string? LimitId,
        string? LimitType,
        string? LimitCategory,
        string? LimitDirection,
        string? MeasurementId,
        string? Unit,
        string? ScopeType,
        string? Label,
        string? Description
    );

    public record LoadControlLimitDescriptionListDataType(
        LoadControlLimitDescriptionDataType[]? LoadControlLimitDescriptionData
    );

    public record LoadControlLimitDescriptionListDataSelectorsType(
        uint? LimitId,
        LoadControlLimitTypeEnumType? LimitType,
        string? LimitDirection,
        uint? MeasurementId,
        string? ScopeType
    );
}
