// <auto-generated>
// This file was generated from EEBus_SPINE_TS_Measurement.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum MeasurementTypeEnumType
    {
        acceleration,
        angle,
        angularVelocity,
        area,
        atmosphericPressure,
        capacity,
        concentration,
        count,
        current,
        density,
        distance,
        electricField,
        energy,
        force,
        frequency,
        harmonicDistortion,
        heat,
        heatFlux,
        illuminance,
        impulse,
        level,
        magneticField,
        mass,
        massFlow,
        particles,
        percentage,
        power,
        powerFactor,
        pressure,
        radonActivity,
        relativeHumidity,
        resistance,
        solarRadiation,
        speed,
        temperature,
        time,
        torque,
        unknown,
        velocity,
        voltage,
        volume,
        volumetricFlow
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum MeasurementValueTypeEnumType
    {
        value,
        averageValue,
        minValue,
        maxValue,
        standardDeviation
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum MeasurementValueSourceEnumType
    {
        measuredValue,
        calculatedValue,
        empiricalValue
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum MeasurementValueTendencyEnumType
    {
        rising,
        stable,
        falling
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum MeasurementValueStateEnumType
    {
        normal,
        outOfRange,
        error
    }

    public record MeasurementDataType(
        uint? MeasurementId,
        MeasurementValueTypeEnumType? ValueType,
        string? Timestamp,
        decimal? Value,
        string? EvaluationPeriod,
        MeasurementValueSourceEnumType? ValueSource,
        MeasurementValueTendencyEnumType? ValueTendency,
        MeasurementValueStateEnumType? ValueState
    );

    public record MeasurementDataElementsType(
        string? MeasurementId,
        string? ValueType,
        string? Timestamp,
        string? Value,
        string? EvaluationPeriod,
        string? ValueSource,
        string? ValueTendency,
        string? ValueState
    );

    public record MeasurementListDataType(
        MeasurementDataType[]? MeasurementData
    );

    public record MeasurementListDataSelectorsType(
        uint? MeasurementId,
        MeasurementValueTypeEnumType? ValueType,
        string? TimestampInterval
    );

    public record MeasurementSeriesDataType(
        uint? MeasurementId,
        MeasurementValueTypeEnumType? ValueType,
        string? Timestamp,
        decimal? Value,
        string? EvaluationPeriod,
        MeasurementValueSourceEnumType? ValueSource,
        MeasurementValueTendencyEnumType? ValueTendency,
        MeasurementValueStateEnumType? ValueState
    );

    public record MeasurementSeriesDataElementsType(
        string? MeasurementId,
        string? ValueType,
        string? Timestamp,
        string? Value,
        string? EvaluationPeriod,
        string? ValueSource,
        string? ValueTendency,
        string? ValueState
    );

    public record MeasurementSeriesListDataType(
        MeasurementSeriesDataType[]? MeasurementSeriesData
    );

    // ...additional types for constraints, description, threshold relation, etc. would follow the same pattern
}
