// <auto-generated>
// This file was generated from EEBus_SPINE_TS_Messaging.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum MessagingTypeEnumType
    {
        logging,
        information,
        warning,
        alarm,
        emergency,
        obsolete
    }

    public record MessagingDataType(
        string? Timestamp,
        uint? MessagingNumber,
        MessagingTypeEnumType? Type,
        string? Text
    );

    public record MessagingDataElementsType(
        string? Timestamp,
        string? MessagingNumber,
        string? Type,
        string? Text
    );

    public record MessagingListDataType(
        MessagingDataType[]? MessagingData
    );

    public record MessagingListDataSelectorsType(
        string? TimestampInterval,
        uint? MessagingNumber
    );
}
