// <auto-generated>
// This file was generated from EEBus_SPINE_TS_NetworkManagement.xsd
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum NetworkManagementFeatureSetType
    {
        gateway,
        router,
        smart,
        simple
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum NetworkManagementProcessStateStateType
    {
        succeeded,
        failed,
        aborted
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum NetworkManagementStateChangeType
    {
        added,
        removed,
        modified
    }

    public record NetworkManagementAddNodeCallType(
        string? NodeAddress,
        string? NativeSetup,
        string? Timeout,
        string? Label,
        string? Description
    );

    public record NetworkManagementAddNodeCallElementsType(
        string? NodeAddress,
        string? NativeSetup,
        string? Timeout,
        string? Label,
        string? Description
    );

    public record NetworkManagementRemoveNodeCallType(
        string? NodeAddress,
        string? Timeout
    );

    public record NetworkManagementRemoveNodeCallElementsType(
        string? NodeAddress,
        string? Timeout
    );

    public record NetworkManagementModifyNodeCallType(
        string? NodeAddress,
        string? NativeSetup,
        string? Timeout,
        string? Label,
        string? Description
    );

    public record NetworkManagementModifyNodeCallElementsType(
        string? NodeAddress,
        string? NativeSetup,
        string? Timeout,
        string? Label,
        string? Description
    );

    public record NetworkManagementScanNetworkCallType(
        string? ScanSetup,
        string? Timeout
    );

    public record NetworkManagementScanNetworkCallElementsType(
        string? ScanSetup,
        string? Timeout
    );

    public record NetworkManagementDiscoverCallType(
        string? DiscoverAddress
    );

    public record NetworkManagementDiscoverCallElementsType(
        string? DiscoverAddress
    );

    public record NetworkManagementAbortCallType();
    public record NetworkManagementAbortCallElementsType();

    public record NetworkManagementProcessStateDataType(
        NetworkManagementProcessStateStateType? State,
        string? Description
    );

    public record NetworkManagementProcessStateDataElementsType(
        string? State,
        string? Description
    );

    public record NetworkManagementJoiningModeDataType(
        string? Setup
    );

    public record NetworkManagementJoiningModeDataElementsType(
        string? Setup
    );

    public record NetworkManagementReportCandidateDataType(
        string? CandidateSetup,
        bool? SetupUsableForAdd,
        string? Label,
        string? Description
    );

    public record NetworkManagementReportCandidateDataElementsType(
        string? CandidateSetup,
        string? SetupUsableForAdd,
        string? Label,
        string? Description
    );

    public record NetworkManagementDeviceDescriptionDataType(
        string? DeviceAddress,
        string? DeviceType,
        string? NetworkManagementResponsibleAddress,
        string? NativeSetup,
        string? TechnologyAddress,
        string? CommunicationsTechnologyInformation,
        NetworkManagementFeatureSetType? NetworkFeatureSet,
        NetworkManagementStateChangeType? LastStateChange,
        string? MinimumTrustLevel,
        string? Label,
        string? Description
    );

    public record NetworkManagementDeviceDescriptionDataElementsType(
        string? DeviceAddress,
        string? DeviceType,
        string? NetworkManagementResponsibleAddress,
        string? NativeSetup,
        string? TechnologyAddress,
        string? CommunicationsTechnologyInformation,
        string? NetworkFeatureSet,
        string? LastStateChange,
        string? MinimumTrustLevel,
        string? Label,
        string? Description
    );

    public record NetworkManagementDeviceDescriptionListDataType(
        NetworkManagementDeviceDescriptionDataType[]? NetworkManagementDeviceDescriptionData
    );

    public record NetworkManagementDeviceDescriptionListDataSelectorsType(
        string? DeviceAddress,
        string? DeviceType
    );

    public record NetworkManagementEntityDescriptionDataType(
        string? EntityAddress,
        string? EntityType,
        NetworkManagementStateChangeType? LastStateChange,
        string? MinimumTrustLevel,
        string? Label,
        string? Description
    );

    public record NetworkManagementEntityDescriptionDataElementsType(
        string? EntityAddress,
        string? EntityType,
        string? LastStateChange,
        string? MinimumTrustLevel,
        string? Label,
        string? Description
    );

    public record NetworkManagementEntityDescriptionListDataType(
        NetworkManagementEntityDescriptionDataType[]? NetworkManagementEntityDescriptionData
    );

    public record NetworkManagementEntityDescriptionListDataSelectorsType(
        string? EntityAddress,
        string? EntityType
    );

    public record NetworkManagementFeatureDescriptionDataType(
        string? FeatureAddress,
        string? FeatureType,
        string[]? SpecificUsage,
        string? FeatureGroup,
        string? Role,
        string[]? SupportedFunction,
        NetworkManagementStateChangeType? LastStateChange,
        string? MinimumTrustLevel,
        string? Label,
        string? Description,
        string? MaxResponseDelay
    );

    public record NetworkManagementFeatureDescriptionDataElementsType(
        string? FeatureAddress,
        string? FeatureType,
        string? SpecificUsage,
        string? FeatureGroup,
        string? Role,
        string? SupportedFunction,
        string? LastStateChange,
        string? MinimumTrustLevel,
        string? Label,
        string? Description,
        string? MaxResponseDelay
    );

    public record NetworkManagementFeatureDescriptionListDataType(
        NetworkManagementFeatureDescriptionDataType[]? NetworkManagementFeatureDescriptionData
    );

    public record NetworkManagementFeatureDescriptionListDataSelectorsType(
        string? FeatureAddress,
        string? FeatureType
    );
}
