// <auto-generated>
// This file was generated from EEBus_SPINE_TS_NodeManagement.xsd on 2026-03-02
// JSON-serializable C# records for NodeManagement types
using System.Text.Json.Serialization;

namespace EEBus.Spine;

// NodeManagementSpecificationVersionListType
public record NodeManagementSpecificationVersionListType(
    List<SpecificationVersionDataType>? SpecificationVersion
);

// NodeManagementDetailedDiscoveryDeviceInformationType
public record NodeManagementDetailedDiscoveryDeviceInformationType(
    NodeManagementDetailedDiscoveryDeviceInformationType_Description? Description
);

public record NodeManagementDetailedDiscoveryDeviceInformationType_Description(
    NodeManagementDetailedDiscoveryDeviceInformationType_Description_DeviceAddress? DeviceAddress,
    DeviceTypeType? DeviceType,
    FeatureAddressType? NetworkManagementResponsibleAddress,
    NetworkManagementNativeSetupType? NativeSetup,
    NetworkManagementTechnologyAddressType? TechnologyAddress,
    NetworkManagementCommunicationsTechnologyInformationType? CommunicationsTechnologyInformation,
    NetworkManagementFeatureSetType? NetworkFeatureSet,
    NetworkManagementStateChangeType? LastStateChange,
    NetworkManagementMinimumTrustLevelType? MinimumTrustLevel,
    LabelType? Label,
    DescriptionType? Description
);

public record NodeManagementDetailedDiscoveryDeviceInformationType_Description_DeviceAddress(
    DeviceTypeType? Device
);

// NodeManagementDetailedDiscoveryEntityInformationType
public record NodeManagementDetailedDiscoveryEntityInformationType(
    NodeManagementDetailedDiscoveryEntityInformationType_Description? Description
);

public record NodeManagementDetailedDiscoveryEntityInformationType_Description(
    NodeManagementDetailedDiscoveryEntityInformationType_Description_EntityAddress? EntityAddress,
    EntityTypeType? EntityType,
    NetworkManagementStateChangeType? LastStateChange,
    NetworkManagementMinimumTrustLevelType? MinimumTrustLevel,
    LabelType? Label,
    DescriptionType? Description
);

public record NodeManagementDetailedDiscoveryEntityInformationType_Description_EntityAddress(
    List<EntityTypeType>? Entity
);

// NodeManagementDetailedDiscoveryFeatureInformationType
public record NodeManagementDetailedDiscoveryFeatureInformationType(
    NodeManagementDetailedDiscoveryFeatureInformationType_Description? Description
);

public record NodeManagementDetailedDiscoveryFeatureInformationType_Description(
    NodeManagementDetailedDiscoveryFeatureInformationType_Description_FeatureAddress? FeatureAddress,
    FeatureTypeType? FeatureType,
    List<FeatureSpecificUsageType>? SpecificUsage,
    FeatureGroupType? FeatureGroup,
    RoleType? Role,
    List<FunctionPropertyType>? SupportedFunction,
    NetworkManagementStateChangeType? LastStateChange,
    NetworkManagementMinimumTrustLevelType? MinimumTrustLevel,
    LabelType? Label,
    DescriptionType? Description,
    MaxResponseDelayType? MaxResponseDelay
);

public record NodeManagementDetailedDiscoveryFeatureInformationType_Description_FeatureAddress(
    List<EntityTypeType>? Entity,
    FeatureTypeType? Feature
);

// NodeManagementDetailedDiscoveryDataType
public record NodeManagementDetailedDiscoveryDataType(
    NodeManagementSpecificationVersionListType? SpecificationVersionList,
    NodeManagementDetailedDiscoveryDeviceInformationType? DeviceInformation,
    List<NodeManagementDetailedDiscoveryEntityInformationType>? EntityInformation,
    List<NodeManagementDetailedDiscoveryFeatureInformationType>? FeatureInformation
);

// NodeManagementBindingDataType
public record NodeManagementBindingDataType(
    List<BindingManagementEntryDataType>? BindingEntry
);

// NodeManagementBindingRequestCallType
public record NodeManagementBindingRequestCallType(
    BindingManagementRequestCallType? BindingRequest
);

// NodeManagementBindingDeleteCallType
public record NodeManagementBindingDeleteCallType(
    BindingManagementDeleteCallType? BindingDelete
);

// NodeManagementSubscriptionDataType
public record NodeManagementSubscriptionDataType(
    List<SubscriptionManagementEntryDataType>? SubscriptionEntry
);

// NodeManagementSubscriptionRequestCallType
public record NodeManagementSubscriptionRequestCallType(
    SubscriptionManagementRequestCallType? SubscriptionRequest
);

// NodeManagementSubscriptionDeleteCallType
public record NodeManagementSubscriptionDeleteCallType(
    SubscriptionManagementDeleteCallType? SubscriptionDelete
);

// NodeManagementDestinationDataType
public record NodeManagementDestinationDataType(
    NetworkManagementDeviceDescriptionDataType? DeviceDescription
);

// NodeManagementDestinationListDataType
public record NodeManagementDestinationListDataType(
    List<NodeManagementDestinationDataType>? NodeManagementDestinationData
);

// NodeManagementUseCaseDataType
public record NodeManagementUseCaseDataType(
    List<UseCaseInformationDataType>? UseCaseInformation
);

// ...additional records for ElementsType, SelectorsType, BindingDataType, SubscriptionDataType, DestinationDataType, UseCaseDataType, etc. would follow the same pattern, mapping each XSD type to a C# record with nullable properties and appropriate collections.
// For brevity, only the main types are shown here. Extend as needed for full coverage.
// </auto-generated>
