// <auto-generated>
//     Generated from EEBus_SPINE_TS_OperatingConstraints.xsd
//     Date: 2026-03-02
// </auto-generated>
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record OperatingConstraintsInterruptDataType(
        PowerSequenceIdType? SequenceId,
        bool? IsPausable,
        bool? IsStoppable,
        bool? NotInterruptibleAtHighPower,
        uint? MaxCyclesPerDay
    );

    public record OperatingConstraintsInterruptListDataType(
        List<OperatingConstraintsInterruptDataType>? OperatingConstraintsInterruptData
    );

    public record OperatingConstraintsDurationDataType(
        PowerSequenceIdType? SequenceId,
        string? ActiveDurationMin,
        string? ActiveDurationMax,
        string? PauseDurationMin,
        string? PauseDurationMax,
        string? ActiveDurationSumMin,
        string? ActiveDurationSumMax
    );

    public record OperatingConstraintsDurationListDataType(
        List<OperatingConstraintsDurationDataType>? OperatingConstraintsDurationData
    );

    public record OperatingConstraintsPowerDescriptionDataType(
        PowerSequenceIdType? SequenceId,
        EnergyDirectionType? PositiveEnergyDirection,
        UnitOfMeasurementType? PowerUnit,
        UnitOfMeasurementType? EnergyUnit,
        DescriptionType? Description
    );

    public record OperatingConstraintsPowerDescriptionListDataType(
        List<OperatingConstraintsPowerDescriptionDataType>? OperatingConstraintsPowerDescriptionData
    );

    public record OperatingConstraintsPowerRangeDataType(
        PowerSequenceIdType? SequenceId,
        ScaledNumberType? PowerMin,
        ScaledNumberType? PowerMax,
        ScaledNumberType? EnergyMin,
        ScaledNumberType? EnergyMax
    );

    public record OperatingConstraintsPowerRangeListDataType(
        List<OperatingConstraintsPowerRangeDataType>? OperatingConstraintsPowerRangeData
    );

    public record OperatingConstraintsPowerLevelDataType(
        PowerSequenceIdType? SequenceId,
        List<ScaledNumberType>? Power
    );

    public record OperatingConstraintsPowerLevelListDataType(
        List<OperatingConstraintsPowerLevelDataType>? OperatingConstraintsPowerLevelData
    );

    public record OperatingConstraintsResumeImplicationDataType(
        PowerSequenceIdType? SequenceId,
        ScaledNumberType? ResumeEnergyEstimated,
        UnitOfMeasurementType? EnergyUnit,
        ScaledNumberType? ResumeCostEstimated,
        CurrencyType? Currency
    );

    public record OperatingConstraintsResumeImplicationListDataType(
        List<OperatingConstraintsResumeImplicationDataType>? OperatingConstraintsResumeImplicationData
    );
}
