// <auto-generated>
//     Generated from EEBus_SPINE_TS_PowerSequences.xsd
//     Date: 2026-03-02
// </auto-generated>
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record PowerTimeSlotScheduleDataType(
        uint? SequenceId,
        uint? SlotNumber,
        TimePeriodType? TimePeriod,
        string? DefaultDuration,
        string? DurationUncertainty,
        bool? SlotActivated,
        DescriptionType? Description
    );

    public record PowerTimeSlotScheduleListDataType(
        List<PowerTimeSlotScheduleDataType>? PowerTimeSlotScheduleData
    );

    public record PowerTimeSlotValueDataType(
        uint? SequenceId,
        uint? SlotNumber,
        string? ValueType,
        ScaledNumberType? Value
    );

    public record PowerTimeSlotValueListDataType(
        List<PowerTimeSlotValueDataType>? PowerTimeSlotValueData
    );

    public record PowerTimeSlotScheduleConstraintsDataType(
        uint? SequenceId,
        uint? SlotNumber,
        AbsoluteOrRelativeTimeType? EarliestStartTime,
        AbsoluteOrRelativeTimeType? LatestEndTime,
        string? MinDuration,
        string? MaxDuration,
        bool? OptionalSlot
    );

    public record PowerTimeSlotScheduleConstraintsListDataType(
        List<PowerTimeSlotScheduleConstraintsDataType>? PowerTimeSlotScheduleConstraintsData
    );

    public record PowerSequenceAlternativesRelationDataType(
        uint? AlternativesId,
        List<uint>? SequenceId
    );

    public record PowerSequenceAlternativesRelationListDataType(
        List<PowerSequenceAlternativesRelationDataType>? PowerSequenceAlternativesRelationData
    );

    public record PowerSequenceDescriptionDataType(
        uint? SequenceId,
        DescriptionType? Description,
        EnergyDirectionType? PositiveEnergyDirection,
        UnitOfMeasurementType? PowerUnit,
        UnitOfMeasurementType? EnergyUnit,
        MeasurementValueSourceType? ValueSource,
        string? Scope,
        uint? TaskIdentifier,
        uint? RepetitionsTotal
    );

    public record PowerSequenceDescriptionListDataType(
        List<PowerSequenceDescriptionDataType>? PowerSequenceDescriptionData
    );

    public record PowerSequenceStateDataType(
        uint? SequenceId,
        string? State,
        uint? ActiveSlotNumber,
        string? ElapsedSlotTime,
        string? RemainingSlotTime,
        bool? SequenceRemoteControllable,
        uint? ActiveRepetitionNumber,
        string? RemainingPauseTime
    );

    public record PowerSequenceStateListDataType(
        List<PowerSequenceStateDataType>? PowerSequenceStateData
    );

    public record PowerSequenceScheduleDataType(
        uint? SequenceId,
        AbsoluteOrRelativeTimeType? StartTime,
        AbsoluteOrRelativeTimeType? EndTime
    );

    public record PowerSequenceScheduleListDataType(
        List<PowerSequenceScheduleDataType>? PowerSequenceScheduleData
    );

    public record PowerSequenceScheduleConstraintsDataType(
        uint? SequenceId,
        AbsoluteOrRelativeTimeType? EarliestStartTime,
        AbsoluteOrRelativeTimeType? LatestStartTime,
        AbsoluteOrRelativeTimeType? EarliestEndTime,
        AbsoluteOrRelativeTimeType? LatestEndTime,
        bool? OptionalSequence
    );

    public record PowerSequenceScheduleConstraintsListDataType(
        List<PowerSequenceScheduleConstraintsDataType>? PowerSequenceScheduleConstraintsData
    );

    public record PowerSequencePriceDataType(
        uint? SequenceId,
        AbsoluteOrRelativeTimeType? PotentialStartTime,
        ScaledNumberType? Price,
        CurrencyType? Currency
    );

    public record PowerSequencePriceListDataType(
        List<PowerSequencePriceDataType>? PowerSequencePriceData
    );

    public record PowerSequenceSchedulePreferenceDataType(
        uint? SequenceId,
        bool? Greenest,
        bool? Cheapest
    );

    public record PowerSequenceSchedulePreferenceListDataType(
        List<PowerSequenceSchedulePreferenceDataType>? PowerSequenceSchedulePreferenceData
    );

    public record PowerSequenceNodeScheduleInformationDataType(
        bool? NodeRemoteControllable,
        bool? SupportsSingleSlotSchedulingOnly,
        uint? AlternativesCount,
        uint? TotalSequencesCountMax,
        bool? SupportsReselection
    );
}
