// <auto-generated>
//     Generated from EEBus_SPINE_TS_Sensing.xsd
//     Date: 2026-03-02
// </auto-generated>
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record SensingDataType(
        AbsoluteOrRelativeTimeType? Timestamp,
        string? State,
        ScaledNumberType? Value
    );

    public record SensingListDataType(
        List<SensingDataType>? SensingData
    );

    public record SensingDescriptionDataType(
        string? SensingType,
        UnitOfMeasurementType? Unit,
        ScopeTypeType? ScopeType,
        LabelType? Label,
        DescriptionType? Description
    );
}
