// <auto-generated>
//     Generated from EEBus_SPINE_TS_Setpoint.xsd
//     Date: 2026-03-02
// </auto-generated>
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record SetpointDataType(
        uint? SetpointId,
        ScaledNumberType? Value,
        ScaledNumberType? ValueMin,
        ScaledNumberType? ValueMax,
        ScaledNumberType? ValueToleranceAbsolute,
        ScaledNumberType? ValueTolerancePercentage,
        bool? IsSetpointChangeable,
        bool? IsSetpointActive,
        TimePeriodType? TimePeriod
    );

    public record SetpointListDataType(
        List<SetpointDataType>? SetpointData
    );

    public record SetpointConstraintsDataType(
        uint? SetpointId,
        ScaledNumberType? SetpointRangeMin,
        ScaledNumberType? SetpointRangeMax,
        ScaledNumberType? SetpointStepSize
    );

    public record SetpointConstraintsListDataType(
        List<SetpointConstraintsDataType>? SetpointConstraintsData
    );

    public record SetpointDescriptionDataType(
        uint? SetpointId,
        uint? MeasurementId,
        uint? TimeTableId,
        string? SetpointType,
        UnitOfMeasurementType? Unit,
        ScopeTypeType? ScopeType,
        LabelType? Label,
        DescriptionType? Description
    );

    public record SetpointDescriptionListDataType(
        List<SetpointDescriptionDataType>? SetpointDescriptionData
    );
}
