// <auto-generated>
//     Generated from EEBus_SPINE_TS_SmartEnergyManagementPs.xsd
//     Date: 2026-03-02
// </auto-generated>
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record SmartEnergyManagementPsAlternativesRelationType(
        uint? AlternativesId
    );

    public record SmartEnergyManagementPsPowerSequenceType(
        SmartEnergyManagementPsPowerSequenceDescription? Description,
        SmartEnergyManagementPsPowerSequenceState? State,
        SmartEnergyManagementPsPowerSequenceSchedule? Schedule,
        SmartEnergyManagementPsPowerSequenceScheduleConstraints? ScheduleConstraints,
        SmartEnergyManagementPsPowerSequenceSchedulePreference? SchedulePreference,
        SmartEnergyManagementPsOperatingConstraintsInterrupt? OperatingConstraintsInterrupt,
        SmartEnergyManagementPsOperatingConstraintsDuration? OperatingConstraintsDuration,
        SmartEnergyManagementPsOperatingConstraintsResumeImplication? OperatingConstraintsResumeImplication,
        List<SmartEnergyManagementPsPowerTimeSlotType>? PowerTimeSlot
    );

    public record SmartEnergyManagementPsAlternativesType(
        SmartEnergyManagementPsAlternativesRelationType? Relation,
        List<SmartEnergyManagementPsPowerSequenceType>? PowerSequence
    );

    public record SmartEnergyManagementPsPowerSequenceDescription(
        uint? SequenceId,
        string? Description,
        UnitOfMeasurementType? PowerUnit,
        UnitOfMeasurementType? EnergyUnit,
        MeasurementValueSourceType? ValueSource,
        uint? TaskIdentifier,
        uint? RepetitionsTotal
    );

    public record SmartEnergyManagementPsPowerSequenceState(
        string? State,
        uint? ActiveSlotNumber,
        string? ElapsedSlotTime,
        string? RemainingSlotTime,
        bool? SequenceRemoteControllable,
        uint? ActiveRepetitionNumber,
        string? RemainingPauseTime
    );

    public record SmartEnergyManagementPsPowerSequenceSchedule(
        string? StartTime,
        string? EndTime
    );

    public record SmartEnergyManagementPsPowerSequenceScheduleConstraints(
        string? EarliestStartTime,
        string? LatestEndTime
    );

    public record SmartEnergyManagementPsPowerSequenceSchedulePreference(
        bool? Greenest,
        bool? Cheapest
    );

    public record SmartEnergyManagementPsOperatingConstraintsInterrupt(
        bool? IsPausable,
        bool? IsStoppable,
        uint? MaxCyclesPerDay
    );

    public record SmartEnergyManagementPsOperatingConstraintsDuration(
        string? ActiveDurationMin,
        string? ActiveDurationMax,
        string? PauseDurationMin,
        string? PauseDurationMax,
        string? ActiveDurationSumMin,
        string? ActiveDurationSumMax
    );

    public record SmartEnergyManagementPsOperatingConstraintsResumeImplication(
        ScaledNumberType? ResumeEnergyEstimated,
        UnitOfMeasurementType? EnergyUnit,
        ScaledNumberType? ResumeCostEstimated,
        CurrencyType? Currency
    );

    public record SmartEnergyManagementPsPowerTimeSlotType(
        SmartEnergyManagementPsPowerTimeSlotSchedule? Schedule,
        SmartEnergyManagementPsPowerTimeSlotValueListType? ValueList,
        SmartEnergyManagementPsPowerTimeSlotScheduleConstraints? ScheduleConstraints
    );

    public record SmartEnergyManagementPsPowerTimeSlotSchedule(
        uint? SlotNumber,
        SmartEnergyManagementPsTimePeriod? TimePeriod,
        string? DefaultDuration,
        string? DurationUncertainty,
        bool? SlotActivated,
        string? Description
    );

    public record SmartEnergyManagementPsTimePeriod(
        string? StartTime,
        string? EndTime
    );

    public record SmartEnergyManagementPsPowerTimeSlotValueListType(
        List<SmartEnergyManagementPsPowerTimeSlotValue>? Value
    );

    public record SmartEnergyManagementPsPowerTimeSlotValue(
        string? ValueType,
        ScaledNumberType? Value
    );

    public record SmartEnergyManagementPsPowerTimeSlotScheduleConstraints(
        string? EarliestStartTime,
        string? LatestEndTime,
        string? MinDuration,
        string? MaxDuration,
        bool? OptionalSlot
    );

    public record SmartEnergyManagementPsDataType(
        SmartEnergyManagementPsNodeScheduleInformation? NodeScheduleInformation,
        List<SmartEnergyManagementPsAlternativesType>? Alternatives
    );

    public record SmartEnergyManagementPsNodeScheduleInformation(
        bool? NodeRemoteControllable,
        bool? SupportsSingleSlotSchedulingOnly,
        uint? AlternativesCount,
        uint? TotalSequencesCountMax,
        bool? SupportsReselection
    );

    public record SmartEnergyManagementPsPriceDataType(
        List<SmartEnergyManagementPsPrice>? Price
    );

    public record SmartEnergyManagementPsPrice(
        uint? SequenceId,
        ScaledNumberType? Price,
        CurrencyType? Currency
    );

    public record SmartEnergyManagementPsConfigurationRequestCallType(
        SmartEnergyManagementPsScheduleConfigurationRequest? ScheduleConfigurationRequest
    );

    public record SmartEnergyManagementPsScheduleConfigurationRequest(
        uint? SequenceId
    );

    public record SmartEnergyManagementPsPriceCalculationRequestCallType(
        SmartEnergyManagementPsPriceCalculationRequest? PriceCalculationRequest
    );

    public record SmartEnergyManagementPsPriceCalculationRequest(
        uint? SequenceId
    );
}
