// <auto-generated>
//     Generated from EEBus_SPINE_TS_StateInformation.xsd
//     Date: 2026-03-02
// </auto-generated>
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record StateInformationDataType(
        uint? StateInformationId,
        string? StateInformation,
        bool? IsActive,
        string? Category,
        AbsoluteOrRelativeTimeType? TimeOfLastChange
    );

    public record StateInformationListDataType(
        List<StateInformationDataType>? StateInformationData
    );
}
