// <auto-generated>
//     Generated from EEBus_SPINE_TS_SubscriptionManagement.xsd
//     Date: 2026-03-02
// </auto-generated>
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record SubscriptionManagementEntryDataType(
        uint? SubscriptionId,
        FeatureAddressType? ClientAddress,
        FeatureAddressType? ServerAddress,
        LabelType? Label,
        DescriptionType? Description
    );

    public record SubscriptionManagementEntryListDataType(
        List<SubscriptionManagementEntryDataType>? SubscriptionManagementEntryData
    );

    public record SubscriptionManagementRequestCallType(
        FeatureAddressType? ClientAddress,
        FeatureAddressType? ServerAddress,
        FeatureTypeType? ServerFeatureType
    );

    public record SubscriptionManagementDeleteCallType(
        uint? SubscriptionId,
        FeatureAddressType? ClientAddress,
        FeatureAddressType? ServerAddress
    );

    public record FeatureAddressType(
        string? Device,
        int[]? Entity,
        int? Feature
    );
}
