// <auto-generated>
//     Generated from EEBus_SPINE_TS_SupplyCondition.xsd
//     Date: 2026-03-02
// </auto-generated>
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record SupplyConditionDataType(
        uint? ConditionId,
        AbsoluteOrRelativeTimeType? Timestamp,
        string? EventType,
        string? Originator,
        uint? ThresholdId,
        ScaledNumberType? ThresholdPercentage,
        TimePeriodType? RelevantPeriod,
        DescriptionType? Description,
        string? GridCondition
    );

    public record SupplyConditionListDataType(
        List<SupplyConditionDataType>? SupplyConditionData
    );

    public record SupplyConditionDescriptionDataType(
        uint? ConditionId,
        string? CommodityType,
        EnergyDirectionType? PositiveEnergyDirection,
        LabelType? Label,
        DescriptionType? Description
    );

    public record SupplyConditionDescriptionListDataType(
        List<SupplyConditionDescriptionDataType>? SupplyConditionDescriptionData
    );

    public record SupplyConditionThresholdRelationDataType(
        uint? ConditionId,
        List<uint>? ThresholdId
    );

    public record SupplyConditionThresholdRelationListDataType(
        List<SupplyConditionThresholdRelationDataType>? SupplyConditionThresholdRelationData
    );
}
