// <auto-generated>
//     Generated from EEBus_SPINE_TS_TariffInformation.xsd
//     Date: 2026-03-02
// </auto-generated>
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record TariffOverallConstraintsDataType(
        uint? MaxTariffCount,
        uint? MaxBoundaryCount,
        uint? MaxTierCount,
        uint? MaxIncentiveCount,
        uint? MaxBoundariesPerTariff,
        uint? MaxTiersPerTariff,
        uint? MaxBoundariesPerTier,
        uint? MaxIncentivesPerTier
    );

    public record TariffDataType(
        uint? TariffId,
        List<uint>? ActiveTierId
    );

    public record TariffListDataType(
        List<TariffDataType>? TariffData
    );

    public record TariffTierRelationDataType(
        uint? TariffId,
        List<uint>? TierId
    );

    public record TariffTierRelationListDataType(
        List<TariffTierRelationDataType>? TariffTierRelationData
    );

    public record TariffBoundaryRelationDataType(
        uint? TariffId,
        List<uint>? BoundaryId
    );

    public record TariffBoundaryRelationListDataType(
        List<TariffBoundaryRelationDataType>? TariffBoundaryRelationData
    );

    public record TariffDescriptionDataType(
        uint? TariffId,
        uint? CommodityId,
        uint? MeasurementId,
        bool? TariffWriteable,
        bool? UpdateRequired,
        string? ScopeType,
        LabelType? Label,
        DescriptionType? Description,
        bool? SlotIdSupport
    );

    public record TariffDescriptionListDataType(
        List<TariffDescriptionDataType>? TariffDescriptionData
    );

    public record TierBoundaryDataType(
        uint? BoundaryId,
        TimePeriodType? TimePeriod,
        uint? TimeTableId,
        ScaledNumberType? LowerBoundaryValue,
        ScaledNumberType? UpperBoundaryValue
    );

    public record TierBoundaryListDataType(
        List<TierBoundaryDataType>? TierBoundaryData
    );

    public record TierBoundaryDescriptionDataType(
        uint? BoundaryId,
        string? BoundaryType,
        uint? ValidForTierId,
        uint? SwitchToTierIdWhenLower,
        uint? SwitchToTierIdWhenHigher,
        UnitOfMeasurementType? BoundaryUnit,
        LabelType? Label,
        DescriptionType? Description
    );

    public record TierBoundaryDescriptionListDataType(
        List<TierBoundaryDescriptionDataType>? TierBoundaryDescriptionData
    );

    public record CommodityDataType(
        uint? CommodityId,
        string? CommodityType,
        EnergyDirectionType? PositiveEnergyDirection,
        LabelType? Label,
        DescriptionType? Description
    );

    public record CommodityListDataType(
        List<CommodityDataType>? CommodityData
    );

    public record TierDataType(
        uint? TierId,
        TimePeriodType? TimePeriod,
        uint? TimeTableId,
        List<uint>? ActiveIncentiveId
    );

    public record TierListDataType(
        List<TierDataType>? TierData
    );

    public record TierIncentiveRelationDataType(
        uint? TierId,
        List<uint>? IncentiveId
    );

    public record TierIncentiveRelationListDataType(
        List<TierIncentiveRelationDataType>? TierIncentiveRelationData
    );

    public record TierDescriptionDataType(
        uint? TierId,
        string? TierType,
        LabelType? Label,
        DescriptionType? Description
    );

    public record TierDescriptionListDataType(
        List<TierDescriptionDataType>? TierDescriptionData
    );

    public record IncentiveDataType(
        uint? IncentiveId,
        string? ValueType,
        AbsoluteOrRelativeTimeType? Timestamp,
        TimePeriodType? TimePeriod,
        uint? TimeTableId,
        ScaledNumberType? Value
    );

    public record IncentiveListDataType(
        List<IncentiveDataType>? IncentiveData
    );

    public record IncentiveDescriptionDataType(
        uint? IncentiveId,
        string? IncentiveType,
        uint? IncentivePriority,
        CurrencyType? Currency,
        UnitOfMeasurementType? Unit,
        LabelType? Label,
        DescriptionType? Description
    );

    public record IncentiveDescriptionListDataType(
        List<IncentiveDescriptionDataType>? IncentiveDescriptionData
    );
}
