// <auto-generated>
//     Generated from EEBus_SPINE_TS_TaskManagement.xsd
//     Date: 2026-03-02
// </auto-generated>
using System.Text.Json.Serialization;

namespace EEBus.Spine
{
    public record TaskManagementJobDataType(
        uint? JobId,
        AbsoluteOrRelativeTimeType? Timestamp,
        string? JobState,
        string? ElapsedTime,
        string? RemainingTime
    );

    public record TaskManagementJobListDataType(
        List<TaskManagementJobDataType>? TaskManagementJobData
    );

    public record TaskManagementJobRelationDataType(
        uint? JobId,
        TaskManagementDirectControlRelatedType? DirectControlRelated,
        TaskManagementHvacRelatedType? HvacRelated,
        TaskManagementLoadControlReleatedType? LoadControlReleated,
        TaskManagementPowerSequencesRelatedType? PowerSequencesRelated,
        TaskManagementSmartEnergyManagementPsRelatedType? SmartEnergyManagementPsRelated
    );

    public record TaskManagementJobRelationListDataType(
        List<TaskManagementJobRelationDataType>? TaskManagementJobRelationData
    );

    public record TaskManagementJobDescriptionDataType(
        uint? JobId,
        string? JobSource,
        LabelType? Label,
        DescriptionType? Description
    );

    public record TaskManagementJobDescriptionListDataType(
        List<TaskManagementJobDescriptionDataType>? TaskManagementJobDescriptionData
    );

    public record TaskManagementOverviewDataType(
        bool? RemoteControllable,
        bool? JobsActive
    );
}
